import { createClient } from '@/lib/server';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { attendanceId, notes } = await request.json();

    if (!attendanceId) {
      return NextResponse.json(
        { error: 'Attendance ID is required' },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // Get the current user - using getUser() for better security
    const { data: { user }, error: userError } = await supabase.auth.getUser();

    if (userError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Check if user is admin or faculty
    const { data: userProfile, error: profileError } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single();

    if (profileError || !userProfile) {
      return NextResponse.json(
        { error: 'User profile not found' },
        { status: 404 }
      );
    }

    if (userProfile.role !== 'admin' && userProfile.role !== 'faculty') {
      return NextResponse.json(
        { error: 'Unauthorized. Only admins and faculty can approve attendance' },
        { status: 403 }
      );
    }

    // Update attendance record
    const { data: updatedAttendance, error: updateError } = await supabase
      .from('session_attendance')
      .update({
        status: 'approved',
        approved_by: user.id,
        approved_at: new Date().toISOString(),
        notes: notes || null
      })
      .eq('id', attendanceId)
      .select()
      .single();

    if (updateError) {
      console.error('Error approving attendance:', updateError);
      return NextResponse.json(
        { error: 'Failed to approve attendance' },
        { status: 500 }
      );
    }

    // The certificate will be automatically generated by the database trigger
    // Check if a certificate was generated for this attendance
    const { data: certificate, error: certificateError } = await supabase
      .from('certificates')
      .select('id, certificate_number')
      .eq('attendance_id', attendanceId)
      .single();

    // We don't need to handle the error here, as the certificate might not exist yet
    // due to timing issues with the trigger

    return NextResponse.json({
      message: 'Attendance approved successfully',
      data: updatedAttendance,
      certificate: certificate || null,
      certificateAvailable: !!certificate
    });

  } catch (error) {
    console.error('Error processing attendance approval:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
